import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useLanguageQuery } from 'next-export-i18n';
import styles from '../styles/Home.module.css';
import { LangSwitcher } from '../components/LangSwitcher';

const Home: NextPage = () => {
  const [query] = useLanguageQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p>
          <Link href={{ pathname: '/about', query: query }} passHref>
            about
          </Link>
        </p>
        <LangSwitcher />
      </main>
    </div>
  );
};

export default Home;
